name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".editorconfig"
      - ".gitattributes"
      - ".gitignore"
      - "LICENSE.md"
      - "README.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - ".editorconfig"
      - ".gitattributes"
      - ".gitignore"
      - "LICENSE.md"
      - "README.md"

jobs:
  codestyle:
    name: "Codestyle check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/composite-actions/setup
        with:
          php: "7.4"

      - name: Run PhpCsFixer
        run: vendor/bin/php-cs-fixer check

  rector:
    name: "Rector check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/composite-actions/setup
        with:
          php: "7.4"

      - name: Run Rector
        run: vendor/bin/rector process --dry-run

  tests:
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --name=mysql
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-retries=3
          --health-timeout=5s

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2", "8.3", "8.4", "8.5"]

    name: PHP ${{ matrix.php }} checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/composite-actions/setup
        with:
          php: ${{ matrix.php }}

      - name: Run tests
        run: vendor/bin/phpunit -c phpunit.dist.xml

      - name: Run PHPStan
        run: vendor/bin/phpstan
